Cliente = input("Ingrese el nombre del cliente: ")
Documento_identidad = int(input("Ingrese el número de documento de identidad del cliente: "))
Producto = input("Ingrese el nombre del producto: ")
Precio_unitario = float(input("Ingrese el precio unitario del producto: "))
Cantidad = int(input("Ingrese la cantidad vendida: "))
Total_venta = Cantidad * Precio_unitario

header = ("="*20 + " TIENDAB " + 20* "=")
print("\n"+header)
print("\n" + "=" * 15 + " FACTURA DE VENTA " + 16 * "="+"\n")
print("\n" f"Cliente: {Cliente.upper()}")
print(f"Documento de identidad: {Documento_identidad}""\n")
print("_" * len(header) + "\n")
print(f"{"Producto:":<25} | {Producto:<10}")
print(f"{"Precio unitario:":<25} | ${Precio_unitario:<10,.0f}")
print(f"{"Cantidad:":<25} | {Cantidad:<10}")
print(f"{"Total de la venta:":<25} | ${Total_venta:<10,.0f}""\n")
print("_" * len(header) + "\n")
print("Gracias por su compra, vuelva pronto!")